// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineFight.Model;

namespace OnlineFight.Migrations
{
    [DbContext(typeof(DbFightContext))]
    partial class DbFightContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("OnlineFight.Model.Combat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LoserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WinnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LoserId");

                    b.HasIndex("WinnerId");

                    b.ToTable("Combats");
                });

            modelBuilder.Entity("OnlineFight.Model.Historique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CombatId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Degat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Turn")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("personnageACtifId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("personnagePassifId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("personnageACtifId");

                    b.HasIndex("personnagePassifId");

                    b.ToTable("Historiques");
                });

            modelBuilder.Entity("OnlineFight.Model.Personnage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attaque")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Defense")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pv")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PvMax")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Personnages");
                });

            modelBuilder.Entity("OnlineFight.Model.Combat", b =>
                {
                    b.HasOne("OnlineFight.Model.Personnage", "Loser")
                        .WithMany()
                        .HasForeignKey("LoserId");

                    b.HasOne("OnlineFight.Model.Personnage", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId");
                });

            modelBuilder.Entity("OnlineFight.Model.Historique", b =>
                {
                    b.HasOne("OnlineFight.Model.Personnage", "personnageACtif")
                        .WithMany()
                        .HasForeignKey("personnageACtifId");

                    b.HasOne("OnlineFight.Model.Personnage", "personnagePassif")
                        .WithMany()
                        .HasForeignKey("personnagePassifId");
                });
#pragma warning restore 612, 618
        }
    }
}
